const GAME_CONFIG = {
    GAME_NAME: "Money Mind", COMPANY: "Ekam Group", VERSION: "1.0.0",
    STARS_PER_2_LEVELS: 1,
    STARS_FOR_10_RUPEES: 100, RUPEES_PER_100_STARS: 10,
    MAX_WITHDRAWALS_PER_MONTH: 1, MIN_WITHDRAWAL_RUPEES: 100,
    MISTAKES_FOR_SCRATCH: 5,
    SCRATCH_DEFAULT_STARS: 1,
    SCRATCH_BONUS_STARS: 2,
    BONUS_THRESHOLD: 6,
    REFERRAL_REWARD_STARS: 5,
    REFERRAL_TRIGGER_AT: 50,
    LEVEL_TIME_MS: 3000,
    MAX_LIVES: 3,
    ENCRYPTION_KEY: "EkamGroup_MM_2026_SecureKey_XYZ!",
    ADMIN_PASSWORD: "EkamGroup@2024!"
};
